---
title: "Generating synthetic data using `stpp` package in R"
author: "geoMADE"
date: "19 October 2017"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

In R environment, the **stpp** package is the only package that provides the functions for synthesizing point process in space and time over a wide class of models. For the purpose of this post, we will look at three models, namely; the Homogeneous Poisson Process (HPP), Inhomogeneous Poisson Process (IHPP), and Poisson cluster process (PCP). These models are chosen because of their relevance from the viewpoint of crime data analytics. These will be discussed along with their formulations. 

The `rpp` function is used to synthesise point process based on the HPP and IHPP models, while the ` rpcp` function is used to synthesise point process based on the PCP model. In this exercise, the point processes are generated within a 3D region defined spatially by the geographical boundary of South Chicago, and temporally by one year time interval i.e. $t =c(1, 365)$.

**1. Homogeneous Poisson process (HPP)**

The simplest stochastic model for generating STPP. It is generally used as the benchmark of complete spatio-temporal randomness (CSTR). Given a spatio-temporal region $S\times T$, the events form an independent random sample from the uniform distribution on $S\times T$. Hence, a homogenous Poisson process can be defined more formally by the following postulations:
(i)	For some intensity $\lambda \ge 0$, the number $Y(S\times T)$ of events within the region $S\times T$ is defined by a Poisson distribution with mean $\lambda |S||T|$, where $|.|$ denotes 2D area.
(ii)	Given $Y(S\times T)=n$, the events form an independent random sample from the uniform distribution on $S\times T$.

  *Properties:*
The $1^{st}-order$ and $2^{nd}-order$ intensities are the constants, $\lambda(s,t)=\lambda$ and $\lambda_2((s_i,t_i), (s_j,t_j))=\lambda^2$, respectively. The covariance density is identically zero, and the pair correlation function identically 1, and the STIK function is $K_{ST}(u,v)=\pi u^2v$.

  *Simulation Study:*
  
To synthesise a homogeneous Poisson point process in $S\times T$ using the `rpp` function, two steps are involved, namely; (1) Simulate the number $n=Y(S\times T)$ of points according to Poisson distribution with mean $\lambda|S||T|$, and (2) Sample each of the $n$ locations and $n$ times according to a uniform distribution on $S$ and on $T$ respectively.